title: "Les recettes de Mamie"
description: "Carnet de cuisine de famille"
url: "https://yohanobadia.github.io"
baseurl: "/Mamie%20Recettes"

remote_theme: "mmistakes/so-simple-theme"

collections:
  recipes:
    output: true
    permalink: /recettes/:name/

defaults:
  - scope:
      path: ""
      type: "recipes"
    values:
      layout: recipe

markdown: kramdown
highlighter: rouge

sass:
  sass_dir: assets/css
